### ISSUE TITLE
화면구현 - Company

### ISSUE THREAD

**Issue by khm9990503** [khm9990503/Kmarket2#41]
// company

- [x] http://chhak.click/Kmarket/company/index.html

- [x] http://chhak.click/Kmarket/company/introduce.html

- [x] http://chhak.click/Kmarket/company/notice.html

- [x] http://chhak.click/Kmarket/company/promote.html

- [x] http://chhak.click/Kmarket/company/manage.html

**Comment by haerisogyumo** [comment]
2023/02/13 company 화면구현 완료
